git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-
  branch: main
  maintainers:
    # marmarek
    - '0064428F455451B3EBE78A7F063938BA42CFA724'
    # simon
    - '274E12AB03F2FE293765FC06DA0434BC706E1FCF'

backend-vmm: xen
debug: true
verbose: true
qubes-release: r4.3
use-qubes-repo:
  version: 4.3
  testing: false

distributions:
  - vm-trixie
template-root-size: "30G"

templates:
  - ParrotOS-7.0:
      dist: trixie
      flavor: parrot
      options:
        - minimal
        - no-recommends

executor:
  type: qubes
  options:
    dispvm: "executor-dvm"

stages:
  - fetch
  - prep
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
  - upload:
      executor:
        type: local
