git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-
  branch: release4.3
  maintainers:
    # marmarek
    - '0064428F455451B3EBE78A7F063938BA42CFA724'
    # simon
    - '274E12AB03F2FE293765FC06DA0434BC706E1FCF'


gpg-client: qubes-gpg-client-wrapper
sign-key:
  rpm: FDD1B8244731B36C
  deb: FDD1B8244731B36C

backend-vmm: xen
debug: true
verbose: true
qubes-release: r4.3

distributions:
  - vm-questing

templates:
  # Using packages_jammy_minimal.list
  - questing-minimal:
      dist: questing
      flavor: minimal


components:
#  - builder-debian:
#      packages: False
#      branch: main
  - vmm-xen:
      branch: main
  - vmm-xen-guest:
      branch: main
  - core-vchan-xen:
      branch: main
  - core-qubesdb:
      branch: main
  - core-qrexec:
      branch: main
  - linux-utils:
      branch: main
  - core-agent-linux:
      branch: main
  - gui-common:
      branch: main
  - gui-agent-linux:
      branch: main
  - app-linux-split-gpg:
      branch: main
  - app-linux-input-proxy:
      branch: main
  - app-linux-usb-proxy:
      branch: main
  - meta-packages:
      branch: main

executor:
 type: qubes
 options:
   dispvm: "executor-dvm"

stages:
  - fetch
  - prep
  - build
