#!/bin/bash

DESTDIR="$1"

DEFAULT_ARCHLINUX_MIRRORS="http://10.137.0.68:8082/HTTPS///mirror.rackspace.com/archlinux http://10.137.0.68:8082/HTTPS///arch.mirror.constant.com http://10.137.0.68:8082/HTTPS///mirror.f4st.host/archlinux http://10.137.0.68:8082/HTTPS///mirrors.edge.kernel.org/archlinux"
ARCHLINUX_MIRRORS="${ARCHLINUX_MIRRORS:-$DEFAULT_ARCHLINUX_MIRRORS}"

read -r -a ARCHLINUX_MIRRORS <<< "$ARCHLINUX_MIRRORS"

for MIRROR_ENTRY in "${ARCHLINUX_MIRRORS[@]}"; do
    echo "Server = ${MIRROR_ENTRY%/}/\$repo/os/\$arch"
done > "$DESTDIR/mirrorlist"
